export const GET_JOBS = "GET_JOBS";
export const SET_JOBS_LOADING = "SET_JOBS_LOADING";
export const SET_JOBS_ERORR = "SET_JOBS_ERORR";
export const GET_RELATED_JOBS = "GET_RELATED_JOBS";
export const GET_RELATED_SKILLS = "GET_RELATED_SKILLS";
export const GET_AUTO_COMPELETE = "GET_AUTO_COMPELETE";
export const SET_AUTO_COMPELETE_LOADING = "SET_AUTO_COMPELETE_LOADING";
export const SET_AUTO_COMPELETE_ERROR = "SET_AUTO_COMPELETE_ERROR";
export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";
export const GET_SKILL_RELATED_SKILLS = "GET_SKILL_RELATED_SKILLS";
export const GET_SKILL_RELATED_JOBS = "GET_SKILL_RELATED_JOBS";
export const GET_SKILL_DETAILS = "GET_SKILL_DETAILS";
export const ASSIGN_RELATED_SKILLS_TO_JOBS  = "ASSIGN_RELATED_SKILLS_TO_JOBS";
export const SET_SEARCH_HISTORY  = "SET_SEARCH_HISTORY";


